apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: vikz642/restaurant_repo:v4
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: mongodb+srv://sm:mihi@cluster0.aslaq.mongodb.net/Finace_Tracker
            - name: JWT_SECRET
              value: yourSuperSecretKey
            - name: JWT_EXPIRES_IN
              value: 1h
          volumeMounts:
            - name: uploads
              mountPath: /app/public/uploads
      volumes:
        - name: uploads
          hostPath:
            path: /tmp/restaurant_uploads  # Local host path (adjust for production)
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30004  # Accessible on http://localhost:30001