apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vikz642/auth_repo:v7
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: mongodb+srv://sm:mihi@cluster0.aslaq.mongodb.net/Finace_Tracker
            - name: JWT_SECRET
              value: yourSuperSecretKey
            - name: JWT_EXPIRES_IN
              value: 1h
          volumeMounts:
            - name: uploads
              mountPath: /app/public/uploads
      volumes:
        - name: uploads
          hostPath:
            path: /tmp/auth_uploads  # Local host path (adjust for production)
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30008  # Accessible on http://localhost:30008