apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: vikz642/payment_repo:v3   # Change if using another repo/tag
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: MONGO_URI
              value: mongodb+srv://crazyissa2k:PgjdAjEzSKQGptmG@cluster22.acch1eg.mongodb.net/paymentDB?retryWrites=true&w=majority&appName=Cluster22
            - name: JWT_SECRET
              value: yourSuperSecretKey
            - name: JWT_EXPIRES_IN
              value: 1h
            # Add service discovery env if needed:
            - name: ORDER_API_URL
              value: http://order-service:5005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30003  # Access it at http://localhost:30002